Repository cal-itp/eligibility-server, pull requests merged in 2022-08, with the labels that each got.

#117 Add GitLens and Git Graph extensions
  .devcontainer/devcontainer.json
Labels: chore

#120 Feat: upgrade to Python 3.10
  .devcontainer/Dockerfile
  .devcontainer/compose.yml
  .devcontainer/requirements.txt
  .github/workflows/.python-version
  Dockerfile
  pyproject.toml
Labels: dependencies, chore

#126 Chore: devcontainer setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postAttach.sh
  .devcontainer/requirements.txt
  .dockerignore
  .env.sample
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  bin/init.sh
  bin/start.sh
  compose.yml
  docs/README.md
  docs/getting-started.md
Labels: chore

#134 Chore: fix CI commit format
  .pre-commit-config.yaml
Labels: chore

#123 Feat: production container
  Dockerfile
  bin/init.sh
  bin/start.sh
  compose.yml
  eligibility_server/app.py
Labels: deployment

#136 Feat: configurable keypair via settings
  .markdownlint.yaml
  docs/configuration/settings.md
  eligibility_server/app.py
  eligibility_server/keypair.py
  eligibility_server/settings.py
  eligibility_server/verify.py
  keys/server.pub
  requirements.txt
  tests/conftest.py
  tests/test_app.py
  tests/test_keypair.py
  tests/test_verify.py
Labels: security
