Repository cal-itp/eligibility-server, pull requests merged in 2024-01, with the labels that each got.

#398 Fix: Bugs with Sentry configuration
  eligibility_server/app.py
  eligibility_server/sentry.py
Labels: bug

#397 Fix: published static file location
  .github/workflows/docker-publish.yml
  .gitignore
  Dockerfile
Labels: bug

#409 CI: improve publish workflow
  .github/workflows/docker-publish.yml
Labels: actions, chore, deployment

#410 Chore: ignore .venv directory
  .gitignore
Labels: chore
